# Site settings
title: Cristobal Escobar
author:
  name: Cristobal Escobar
  email: cristobalescobar@wsu.edu
  phone: 253-455-8649
description: Washington State University

# Build settings
remote_theme: jekyll/minima

---
# a comment 
example_key: example value
---

header_pages:
  - about.md
  - portfolio.md
  - contact.md
minima:
  skin: dark (or solarized-dark)
