# Site settings
title: Cristobal Escobar
author:
  name: Cristobal Escobar
  email: cristobalescobar@wsu.edu
description: Mydescription

# Build settings
remote_theme: jekyll/minima

nav_links:
  title: Home url: /
  title: About url: /
  title: Contact url: /

header_pages:
  - about.md
  - portfolio.md
minima:
  skin: dark (or solarized-dark)
