# Site settings
title: Cristobal Escobar
author:
  name: Cristobal Escobar
  email: cristobalescobar@wsu.edu
description: Washington State University

# Build settings
remote_theme: jekyll/minima # mmistakes/jekyll-theme-basically-basic@1.4.5

---
# a comment 

header_pages:
  - index.md
  - portfolio.md
  - about.md
  - contact.md
---
#skin : night
minima:
 skin: dark #(or solarized-dark)
