# Site settings
title: Cristobal Escobar
author:
  name: Cristobal Escobar
  email: cristobalescobar@wsu.edu
phone: 253-455-8649
description: Washington State University

# Build settings
theme: jekyll-theme-slate


header_pages:
  - index.md
  - portfolio.md
  - about.md
  - contact.md

slate:
  skin: dark (or solarized-dark)
