# Site settings
title: Cristobal Escobar
author:
  name: Cristobal Escobar
  email: cristobalescobar@wsu.edu
description: Mydescription

# Build settings
remote_theme: jekyll/minima

---
# a comment 
example_key: example value
---

header_pages:
  - about.md
  - portfolio.md
minima:
  skin: dark (or solarized-dark)
